version: '3.7'

services:
  amc_user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amc_user
    init: true
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      - HOST:127.0.0.1
      - PORT:3100
      - DB_NAME:/amc.db
    networks:
      - amc-network

networks:
  amc-network:
    name: amc-network
    ipam:
      config:
        - subnet: "172.25.0.0/24"
          gateway: "172.25.0.1"